---
- name: Create a deployer user
  hosts: all
  become: true
  tasks:

  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Create a deployer user and add it to the wheel group
    user:
      name: deployer
      groups: wheel
      append: yes
      state: present
      createhome: yes

  - name: Set up authorized keys for the deployer user
    authorized_key: user=deployer key="{{item}}"
    with_file:
      - deployer.pub
