---

- name: Initialize a Kubernetes cluster
  hosts: cluster-master

  tasks:
    - name: Run kubeadm init
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --token a64b93.7ce2f940e0961d56 --kubernetes-version v1.11.0 --apiserver-advertise-address {{ hostvars[inventory_hostname]['ansible_host'] }}
      become: yes

    - name: Remove the Kubernetes configuration directory
      file:
        path=~/.kube
        state=absent

    - name: Create the Kubernetes configuration directory
      file:
        path=~/.kube
        state=directory

    - name: Copy the Kubernetes configuration files
      shell: |
        sudo cp -i /etc/kubernetes/admin.conf ~/.kube/config

    - name: Fix permissions on the Kubernetes configuration file
      shell: |
        sudo chown $(id -u):$(id -g) ~/.kube/config

    - name: Configure networking
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml
